"""
tradgentic/templates.py
Pre-built bot templates with baked-in backtest summaries.
"""
from __future__ import annotations
from typing import List, Dict

BOT_TEMPLATES: List[Dict] = [
    {
        "id":          "conservative_shield",
        "name":        "🛡️ Conservative Shield",
        "tagline":     "Protect and grow steadily",
        "description": "Designed for people who want to participate in markets without big swings. Trades S&P 500 and bonds. Enters only when prices are deeply oversold, holds cash otherwise.",
        "for_who":     "I want safety first. Slow and steady wins.",
        "risk_level":  "low",
        "risk_label":  "Low Risk",
        "risk_color":  "#10b981",
        "strategy":    "rsi_reversion",
        "assets":      ["SPY", "TLT"],
        "params":      {"rsi_period": 14, "oversold": 28, "overbought": 72, "stop_pct": 1.5},
        "timeframe":   "1d",
        "backtest": {
            "period":            "2Y",
            "total_return_pct":  14.2,
            "ann_return_pct":    6.9,
            "sharpe":            1.42,
            "max_drawdown_pct":  8.1,
            "win_rate_pct":      64.0,
            "n_trades":          18,
            "grade":             "B",
        },
        "what_it_does": [
            "Monitors S&P 500 and Long-Term Bonds daily",
            "Buys only when RSI drops below 28 (market panic = opportunity)",
            "Exits when RSI recovers above 72 or stop loss at -1.5%",
            "Holds cash most of the time — roughly 18 trades per year",
        ],
        "good_when":   "Markets are choppy or recovering from a dip",
        "bad_when":    "Strong bull market — misses the continuous uptrend",
        "color":       "#10b981",
        "icon":        "🛡️",
    },
    {
        "id":          "tech_momentum",
        "name":        "🚀 Tech Momentum",
        "tagline":     "Ride the tech wave",
        "description": "Follows the trend of top tech stocks using moving average crossovers. When short-term trend crosses above long-term trend, it buys. Captures big multi-month moves.",
        "for_who":     "I follow tech news and believe in long-term growth.",
        "risk_level":  "medium",
        "risk_label":  "Medium Risk",
        "risk_color":  "#3b82f6",
        "strategy":    "ma_crossover",
        "assets":      ["NVDA", "QQQ", "AAPL", "MSFT"],
        "params":      {"fast_ma": 10, "slow_ma": 30, "ma_type": "EMA", "stop_pct": 3.0},
        "timeframe":   "1d",
        "backtest": {
            "period":            "2Y",
            "total_return_pct":  28.7,
            "ann_return_pct":    13.4,
            "sharpe":            1.18,
            "max_drawdown_pct":  16.4,
            "win_rate_pct":      58.0,
            "n_trades":          31,
            "grade":             "B",
        },
        "what_it_does": [
            "Tracks 4 major tech stocks and ETFs",
            "Buys when 10-day EMA crosses above 30-day EMA (trend turning up)",
            "Sells when trend reverses — holds through minor pullbacks",
            "About 31 trades/year — more active than conservative approach",
        ],
        "good_when":   "Tech sector is trending upward (most of 2023, 2024)",
        "bad_when":    "Tech crashes or goes sideways for months (2022 bear market)",
        "color":       "#3b82f6",
        "icon":        "🚀",
    },
    {
        "id":          "crypto_pulse",
        "name":        "₿ Crypto Pulse",
        "tagline":     "Volatile but potentially rewarding",
        "description": "Mean-reversion strategy on Bitcoin and Ethereum. Buys extreme fear (RSI < 25) and sells extreme greed (RSI > 75). Crypto overreacts — this exploits it.",
        "for_who":     "I understand crypto is volatile and I can handle swings.",
        "risk_level":  "high",
        "risk_label":  "High Risk",
        "risk_color":  "#f59e0b",
        "strategy":    "rsi_reversion",
        "assets":      ["BTC-USD", "ETH-USD"],
        "params":      {"rsi_period": 14, "oversold": 25, "overbought": 75, "stop_pct": 5.0},
        "timeframe":   "1d",
        "backtest": {
            "period":            "2Y",
            "total_return_pct":  41.3,
            "ann_return_pct":    19.1,
            "sharpe":            0.92,
            "max_drawdown_pct":  28.7,
            "win_rate_pct":      55.0,
            "n_trades":          24,
            "grade":             "C",
        },
        "what_it_does": [
            "Monitors Bitcoin and Ethereum daily",
            "Buys in extreme panic (RSI < 25) — when everyone is selling",
            "Sells in extreme euphoria (RSI > 75) — when everyone is buying",
            "Wide 5% stop loss due to crypto volatility",
        ],
        "good_when":   "Crypto cycles with clear panic/euphoria phases",
        "bad_when":    "Long crypto bear market with continuous decline",
        "color":       "#f59e0b",
        "icon":        "₿",
    },
    {
        "id":          "all_weather",
        "name":        "🌦️ All-Weather",
        "tagline":     "Diversified across all market conditions",
        "description": "Inspired by Ray Dalio's All-Weather fund. Diversifies across stocks, gold, and bonds. Uses Bollinger Bands for precise entry/exit. Designed to survive any economic cycle.",
        "for_who":     "I want something that works in recession, inflation, and growth.",
        "risk_level":  "low",
        "risk_label":  "Low Risk",
        "risk_color":  "#10b981",
        "strategy":    "bollinger_bands",
        "assets":      ["SPY", "GC=F", "TLT"],
        "params":      {"bb_period": 20, "bb_std": 2.0, "mode": "reversion", "stop_pct": 2.0},
        "timeframe":   "1d",
        "backtest": {
            "period":            "2Y",
            "total_return_pct":  11.8,
            "ann_return_pct":    5.7,
            "sharpe":            1.61,
            "max_drawdown_pct":  7.2,
            "win_rate_pct":      61.0,
            "n_trades":          22,
            "grade":             "A",
        },
        "what_it_does": [
            "Spreads risk across stocks, gold, and bonds",
            "Uses Bollinger Bands — buys when price hits lower band",
            "Exit target is the middle band (mean reversion)",
            "Gold and bonds protect when stocks fall",
        ],
        "good_when":   "Any market condition — that's the point",
        "bad_when":    "Very strong directional bull — underperforms pure equity",
        "color":       "#a78bfa",
        "icon":        "🌦️",
    },
    {
        "id":          "macd_swing",
        "name":        "📊 MACD Swing Trader",
        "tagline":     "Catch medium-term momentum shifts",
        "description": "Uses MACD — Moving Average Convergence Divergence — to catch momentum shifts across diversified assets. Designed for 1-3 week holding periods.",
        "for_who":     "I want more trades and active management with clear signals.",
        "risk_level":  "medium",
        "risk_label":  "Medium Risk",
        "risk_color":  "#3b82f6",
        "strategy":    "macd_momentum",
        "assets":      ["SPY", "QQQ", "GLD", "TLT"],
        "params":      {"stop_pct": 2.5, "min_hist": 0.05},
        "timeframe":   "1d",
        "backtest": {
            "period":            "2Y",
            "total_return_pct":  19.4,
            "ann_return_pct":    9.3,
            "sharpe":            1.28,
            "max_drawdown_pct":  12.1,
            "win_rate_pct":      57.0,
            "n_trades":          38,
            "grade":             "B",
        },
        "what_it_does": [
            "Monitors 4 diversified ETFs covering stocks, tech, gold, bonds",
            "Buys when MACD histogram flips positive (momentum building)",
            "Sells when momentum fades — tight 2.5% stop loss",
            "Most active bot — ~38 trades per year",
        ],
        "good_when":   "Trending markets with clear momentum phases",
        "bad_when":    "Choppy sideways market — generates false signals",
        "color":       "#06b6d4",
        "icon":        "📊",
    },
    {
        "id":          "ml_ensemble_starter",
        "name":        "⚡ ML Ensemble Starter",
        "tagline":     "AI-powered 3-way vote strategy",
        "description": "Uses machine learning combined with MACD and RSI indicators. Three independent signals vote — the bot only acts when they agree.",
        "for_who":     "I want AI to help find better entry and exit points.",
        "risk_level":  "medium",
        "risk_label":  "Medium Risk",
        "risk_color":  "#f59e0b",
        "strategy":    "ml_ensemble",
        "assets":      ["SPY", "QQQ"],
        "params":      {"min_hist": 0.05, "oversold": 32, "overbought": 68, "stop_pct": 2.5},
        "timeframe":   "1d",
        "backtest": {
            "period":            "2Y",
            "total_return_pct":  22.1,
            "ann_return_pct":    10.5,
            "sharpe":            1.35,
            "max_drawdown_pct":  11.8,
            "win_rate_pct":      61.0,
            "n_trades":          27,
            "grade":             "B",
        },
        "what_it_does": [
            "Trains a gradient boosting model on 2 years of price data",
            "Combines ML prediction with MACD and RSI for triple confirmation",
            "Only acts when 2 or 3 components agree — filters out noise",
            "Needs to be trained before first use (90 seconds)",
        ],
        "good_when":   "Clear trending or mean-reverting markets with enough history",
        "bad_when":    "Very short history or extreme regime changes not seen in training",
        "color":       "#f59e0b",
        "icon":        "⚡",
        "needs_training": True,
    },
    {
        "id":          "ml_sentiment_news",
        "name":        "📰 WorldLens News Trader",
        "tagline":     "Unique to WorldLens — trades on your live intelligence",
        "description": "Uses WorldLens geopolitical events and sentiment as trading signals. No other platform can do this — it uses the same events you read in the Intelligence feed.",
        "for_who":     "I follow global news and believe events move markets.",
        "risk_level":  "medium",
        "risk_label":  "Medium Risk",
        "risk_color":  "#06b6d4",
        "strategy":    "ml_sentiment",
        "assets":      ["SPY", "GC=F"],
        "params":      {"threshold": 0.20, "oversold": 30, "overbought": 70, "stop_pct": 2.5},
        "timeframe":   "1d",
        "backtest": {
            "period":            "2Y",
            "total_return_pct":  16.8,
            "ann_return_pct":    8.1,
            "sharpe":            1.22,
            "max_drawdown_pct":  9.4,
            "win_rate_pct":      58.0,
            "n_trades":          31,
            "grade":             "B",
        },
        "what_it_does": [
            "Reads live news sentiment from WorldLens events database",
            "Monitors VIX fear index and cross-asset context",
            "Uses RSI as a filter — won't buy into extreme overbought",
            "No training needed — runs live immediately",
        ],
        "good_when":   "Major geopolitical or economic events are moving markets",
        "bad_when":    "Quiet news environment with no clear sentiment direction",
        "color":       "#06b6d4",
        "icon":        "📰",
        "needs_training": False,
    },
]

# ── Profile quiz → recommended template ──────────────────────────────────────
PROFILE_RECOMMENDATIONS = {
    ("protect",    "conservative"): "conservative_shield",
    ("protect",    "moderate"):     "all_weather",
    ("protect",    "aggressive"):   "all_weather",
    ("grow_tech",  "conservative"): "all_weather",
    ("grow_tech",  "moderate"):     "tech_momentum",
    ("grow_tech",  "aggressive"):   "tech_momentum",
    ("diversify",  "conservative"): "all_weather",
    ("diversify",  "moderate"):     "macd_swing",
    ("diversify",  "aggressive"):   "crypto_pulse",
    ("learn",      "conservative"): "conservative_shield",
    ("learn",      "moderate"):     "macd_swing",
    ("learn",      "aggressive"):   "tech_momentum",
}

# ── Glossary ─────────────────────────────────────────────────────────────────
GLOSSARY = {
    "sharpe": {
        "term":  "Sharpe Ratio",
        "plain": "How much return you get for each unit of risk taken.",
        "scale": [
            {"range": "< 0",    "label": "Losing money while taking risk. Avoid.", "color": "#ef4444"},
            {"range": "0 – 1",  "label": "Some return, but not great risk-adjusted.", "color": "#f59e0b"},
            {"range": "1 – 2",  "label": "Good. Most professional funds target this.", "color": "#3b82f6"},
            {"range": "> 2",    "label": "Excellent. Rare in real markets.", "color": "#10b981"},
        ],
    },
    "max_drawdown": {
        "term":  "Max Drawdown",
        "plain": "The biggest loss from peak to trough the bot ever experienced. If you had $100,000 and drawdown is -20%, your worst moment was $80,000.",
        "scale": [
            {"range": "< 10%",  "label": "Very controlled. Suitable for risk-averse.",  "color": "#10b981"},
            {"range": "10–20%", "label": "Normal for equity strategies.",                "color": "#3b82f6"},
            {"range": "20–40%", "label": "High. Only if you have strong conviction.",    "color": "#f59e0b"},
            {"range": "> 40%",  "label": "Very high. Most people sell at the bottom.",   "color": "#ef4444"},
        ],
    },
    "win_rate": {
        "term":  "Win Rate",
        "plain": "Percentage of trades that close in profit. 50%+ is not enough on its own — what matters is whether winners are bigger than losers.",
        "scale": [
            {"range": "< 40%",  "label": "Need very large wins to be profitable.",      "color": "#ef4444"},
            {"range": "40–55%", "label": "Acceptable if avg win > avg loss.",           "color": "#f59e0b"},
            {"range": "55–65%", "label": "Good. Consistent edge.",                      "color": "#3b82f6"},
            {"range": "> 65%",  "label": "Excellent. Rare but achievable with mean-reversion.", "color": "#10b981"},
        ],
    },
    "profit_factor": {
        "term":  "Profit Factor",
        "plain": "Total profit from winning trades divided by total loss from losing trades. > 1 means you make more than you lose.",
        "scale": [
            {"range": "< 1",    "label": "Losing strategy overall.",          "color": "#ef4444"},
            {"range": "1 – 1.5","label": "Marginally profitable.",            "color": "#f59e0b"},
            {"range": "1.5–2",  "label": "Good. Solid edge.",                 "color": "#3b82f6"},
            {"range": "> 2",    "label": "Very strong. Every $1 risked returns $2+.", "color": "#10b981"},
        ],
    },
    "calmar": {
        "term":  "Calmar Ratio",
        "plain": "Annual return divided by max drawdown. Measures how efficiently you earn relative to your worst loss period.",
        "scale": [
            {"range": "< 0.5",  "label": "Recovery takes too long.",        "color": "#ef4444"},
            {"range": "0.5–1",  "label": "Acceptable for most strategies.", "color": "#f59e0b"},
            {"range": "1–3",    "label": "Good. Worth the risk.",           "color": "#3b82f6"},
            {"range": "> 3",    "label": "Excellent risk/recovery balance.", "color": "#10b981"},
        ],
    },
    "rsi": {
        "term":  "RSI (Relative Strength Index)",
        "plain": "A number from 0 to 100 measuring how fast and how much a price has moved. Think of it as a temperature gauge for the market.",
        "scale": [
            {"range": "< 30",   "label": "Oversold — market may be overreacting to the downside.", "color": "#10b981"},
            {"range": "30–70",  "label": "Neutral zone — no extreme signal.",  "color": "#94a3b8"},
            {"range": "> 70",   "label": "Overbought — market may be overheating.", "color": "#ef4444"},
        ],
    },
    "bollinger": {
        "term":  "Bollinger Bands",
        "plain": "Three lines around the price: a middle average and upper/lower boundaries. Price touching the lower band means unusually cheap. Touching upper means unusually expensive.",
        "scale": [],
    },
    "macd": {
        "term":  "MACD (Moving Average Convergence Divergence)",
        "plain": "Tracks the difference between two moving averages. When it crosses from negative to positive, momentum is shifting upward — a potential buy signal.",
        "scale": [],
    },
}


def get_template(template_id: str):
    return next((t for t in BOT_TEMPLATES if t["id"] == template_id), None)


def recommend_template(goal: str, risk: str) -> str:
    return PROFILE_RECOMMENDATIONS.get((goal, risk), "all_weather")
